name: Generate snake game

on:
  schedule: # execute every 12 hours
    - cron: "25 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@v2.2.0
        id: snake-gif
        with:
          github_user_name: technologiespro
          svg_out_path: dist/github-contribution-grid-snake2.svg
          l1: '#6229e6'
          l2: '#8257e6'
          l3: '#a187de'
          l4: '#c3b8de'
          empty_color: 'rgba(10,10,10,0.05)'
          snake_color: '#ff5722'

      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}