name: Update stats

on:
  schedule:
    # Runs at 12am UTC
    - cron: "15 */12 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHOW_SHORT_INFO: "True"
          SHOW_LINES_OF_CODE: "True"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_OS: "False"
          SHOW_PROJECTS: "False"
          SHOW_COMMIT: "True"
          SHOW_LANGUAGE: "True"
          SHOW_EDITORS: "False"
          SHOW_TIMEZONE: "False"
          SHOW_LANGUAGE_PER_REPO: "True"
          SHOW_LOC_CHART: "False"